name: Update main with upstream development
on:
  workflow_dispatch:
  schedule:
    - cron: '30 01 * * *'
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
env:
  BRANCH: main
  REPO: bentoml/OpenLLM
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
jobs:
  merge-upstream:
    if: github.repository_owner == 'aarnphm'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
         ref: '${{ env.BRANCH }}'
      - run: sudo apt-get install -y jq curl
      - id: meta
        run: echo "sha=$(curl -SsL "https://api.github.com/repos/${{ env.REPO }}/commits/main" | jq -r ".sha")" >> $GITHUB_OUTPUT
      - run: |
          git config user.name "${{ env.GIT_AUTHOR_NAME }}"
          git config user.email "${{ env.GIT_AUTHOR_EMAIL }}"
          git remote add upstream https://github.com/${{ env.REPO }}.git
          git fetch upstream main
          git merge upstream/main --no-edit --signoff --ff -m "merge: update with upstream [${{ steps.meta.outputs.sha }}]"
          git push origin ${{ env.BRANCH }}
